Added first-chatbot documentation
botpress/documentation pull request #30
Opened 2022-04-05 19:38 UTC by daehli

2022-04-06 20:13 UTC, ptrckbp commented on docs/overview/cloud/first-chatbot.mdx
> +
#Instructions

2022-04-06 20:25 UTC, ptrckbp requested changes

2022-04-06 20:25 UTC, ptrckbp commented on docs/overview/cloud/first-chatbot.mdx
> +
1. Go to botpress's cloud beta
2. Click the download button for your operating system

2022-04-06 20:25 UTC, ptrckbp commented on docs/overview/cloud/first-chatbot.mdx
> +## Create a chatbot in the studio
While you download, Create a ...

2022-04-06 20:25 UTC, ptrckbp commented on docs/overview/cloud/first-chatbot.mdx
> +
Note / attention : You are creating a chatbot on the cloud platform and you'll create a corresponding one in the app, and link them together later.

2022-04-06 20:49 UTC, ptrckbp requested changes

2022-04-06 20:49 UTC, ptrckbp commented on docs/overview/cloud/first-chatbot.mdx
> +2. Copy the keys from the botpress cloud.
key and secret

2022-04-06 20:49 UTC, ptrckbp commented on docs/overview/cloud/first-chatbot.mdx
> +1. Open the botfather on [telegram](https://t.me/botfather)
The botfather is a connector app to build chatbots on Telegram.

2022-04-06 20:49 UTC, ptrckbp commented on docs/overview/cloud/first-chatbot.mdx
> +4. Get the HTTP API from the botfather.
HTTP API -> HTTP API token

Botfather will say something like : Use this token to access the http API

2022-04-06 20:49 UTC, ptrckbp commented on docs/overview/cloud/first-chatbot.mdx
> +3. Create a node text.
Explain that we'll use this to test the chatbot in Telegram later.

2022-04-06 20:49 UTC, ptrckbp commented on docs/overview/cloud/first-chatbot.mdx
> +4. Train your chatbot
Image pointing to the train chatbot button

2022-04-06 20:49 UTC, ptrckbp commented on docs/overview/cloud/first-chatbot.mdx
> +2. Copy the keys from the botpress cloud.
Make sure the user is redirected after clicking "Create bot" there should be a step otherwise

2022-04-06 20:51 UTC, ptrckbp commented on docs/overview/cloud/first-chatbot.mdx
> +## Download the studio binary
Download Botpress 12.27.0 Beta

2022-04-07 19:56 UTC, daehli commented on docs/overview/cloud/first-chatbot.mdx
> +
I put a place holder

2022-04-19 16:18 UTC, merged